import argparse
from pathlib import Path

from .illustration_pipeline import IllustrationGenerator


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate page illustrations from a story JSON using "
            "illustration_prompt + illustration_scene_prompt."
        )
    )
    parser.add_argument(
        "--story_json",
        required=True,
        help="Path to story JSON file generated by this project.",
    )
    parser.add_argument(
        "--output_dir",
        default="",
        help="Output root directory. If omitted, uses the story JSON's parent directory.",
    )
    parser.add_argument(
        "--model_name",
        default="gemini-2.5-flash-image",
        help="Gemini image model name.",
    )
    parser.add_argument(
        "--aspect_ratio",
        default="16:9",
        help="Image aspect ratio (e.g. 16:9, 1:1, 3:4).",
    )
    parser.add_argument(
        "--request_interval_sec",
        type=float,
        default=1.0,
        help="Seconds between image requests.",
    )
    parser.add_argument(
        "--skip_existing",
        action="store_true",
        help="Skip pages if page_XX.* already exists in output illustrations directory.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    story_path = Path(args.story_json)
    if not story_path.exists():
        raise FileNotFoundError(f"Story JSON not found: {story_path}")

    output_dir = args.output_dir.strip() or str(story_path.parent)
    generator = IllustrationGenerator(
        model_name=args.model_name,
        aspect_ratio=args.aspect_ratio,
        request_interval_sec=args.request_interval_sec,
    )
    story = generator.load_story(str(story_path))
    result = generator.generate_from_story(
        story=story,
        output_dir=output_dir,
        skip_existing=args.skip_existing,
    )
    print(
        "Illustration summary: "
        f"total={result['total_tasks']} "
        f"generated={result['generated']} "
        f"skipped={result['skipped']} "
        f"failed={result['failed']} "
        f"manifest={result['manifest_path']}"
    )
